export default async () => {
  return {
    CONVEYOR_LENGTH: process.env.CONVEYOR_LENGTH || 6,
    OVEN_LENGTH: process.env.OVEN_LENGTH || 2,
    OVEN_POSITION: process.env.OVEN_POSITION || 4,
    OVEN_WARMUP_DEGREES_PER_SECOND:
      process.env.OVEN_WARMUP_DEGREES_PER_SECOND || 30,
    OVEN_COOL_DOWN_DEGREES_PER_SECOND:
      process.env.OVEN_COOL_DOWN_DEGREES_PER_SECOND || 10,
    DESIRED_OVEN_TEMPERATURE: process.env.DESIRED_OVEN_TEMPERATURE || 220,
    MOTOR_PULSE_DURATION_SECONDS: process.env.MOTOR_PULSE_DURATION_SECONDS || 1,
  };
};
